### ISSUE TITLE
Is it possible to work with only specific environment?

### ISSUE THREAD

**Issue by noraworld** [Ryooooooga/zabrze#2]
Is it possible to work with only specific environment? For instance: A certain abbreviation only works with macOS, but doesn’t work with Linux.

If not, I was wondering if you could implement this feature because I have abbreviations I would like to work with only on macOS. 🙏

**Comment by Ryooooooga** [comment]
@noraworld 
Added `if:` clause to `abbrevs` #3:

```yaml
abbrevs:
  - name: chrome
    abbr: chrome
    snippet: open -a 'Google Chrome'
    if: '[[ "$OSTYPE" =~ darwin ]]' # only available in macOS
```
