### ISSUE TITLE
How to refer to a current buffer at a snippet

### ISSUE THREAD

**Issue by noraworld** [Ryooooooga/zabrze#8]
I would like to replace some basic commands with GNU ones, on macOS with zabrze, not overriding `$PATH`. But there are so many GNU commands to be installed on my Mac, so I tried to set these command abbreviations all together, but I didn’t know how to achieve this.

What I want to do is something like this:

```yaml
abbrevs:
  - name: GNU commands
    abbr-pattern: ls|mv|cp
    snippet: g((${current_buffer})) # put the "g" prefix at these commands
    if: '[[ "$OSTYPE" =~ darwin ]]'
```

```zsh
$ ls<SP>
# ↓ expanded
$ gls

$ mv<SP>
# ↓ expanded
$ gmv

$ cp<SP>
# ↓ expanded
$ gcp
```

Is it possible? Or, do you know any alternatives to achieve this?

**Comment by Ryooooooga** [comment]
@noraworld 

I don't really recommend, but here is a way:
```yaml
abbrevs:
  - abbr-pattern: ls|mv|cp
    snippet: g${LBUFFER}
    evaluate: true
```

When using abbr-pattern, it would certainly be useful to be able to reference a current buffer.

**Comment by noraworld** [comment]
I gave it a try, and it works successfully! Thank you for your help. 🙏

But I wonder why it is not recommended. Could you please tell me about it?

**Comment by Ryooooooga** [comment]
`cd abc; mv<SP>` becomes `cd abc; gcd abc; mv `.

**Comment by Ryooooooga** [comment]
ah... `abbr-pattern` should be `^(ls|mv|cp)$`.

**Comment by noraworld** [comment]
Oh, that’s true.

How about this one?

```yaml
- abbr-pattern: ^(ls|mv|cp)$
    snippet: g$(echo "$LBUFFER" | gsed -r 's/^.*[;|&&|\|\|](\s*)?//g')
    evaluate: true
```

It worked for me, but do you think it still has problems?

>ah... abbr-pattern should be ^(ls|mv|cp)$.

What types of problems does it cause without putting `^()$`?

**Comment by Ryooooooga** [comment]
>It worked for me, but do you think it still has problems?

Yes, it works. but it is complicated and I would consider adding 3 abbrevs rather than doing that.

>What types of problems does it cause without putting ^()$?

The pattern matches any string contains `ls`, `mv`, or `cp`.

**Comment by noraworld** [comment]
>Yes, it works. but it is complicated and I would consider adding 3 abbrevs rather than doing that.

I agree with you. I also do the same thing if there are a few commands, but there are more than 100 GNU commands to be installed, so I believe it is too redundant.

And... I found an additional problem... `snippet` is fine, but other keys still have a problem. Eventually, I would like to set abbreviations like this:

```yaml
abbrevs:
  - abbr-pattern: ^($(ls $(brew --prefix)/opt/coreutils/bin | grep "^g" | xargs echo | sed -r 's/\s/\|/g'))$ # => ^(g[|gb2sum|gbase32|gbase64|gbasename|gbasenc|gcat|gchcon|gchgrp|gchmod|gchown|gchroot|gcksum|gcomm|gcp|gcsplit|gcut|gdate|gdd|gdf|gdir|gdircolors|gdirname|gdu|gecho|genv|gexpand|gexpr|gfactor|gfalse|gfmt|gfold|ggroups|ghead|ghostid|gid|ginstall|gjoin|gkill|glink|gln|glogname|gls|gmd5sum|gmkdir|gmkfifo|gmknod|gmktemp|gmv|gnice|gnl|gnohup|gnproc|gnumfmt|god|gpaste|gpathchk|gpinky|gpr|gprintenv|gprintf|gptx|gpwd|greadlink|grealpath|grm|grmdir|gruncon|gseq|gsha1sum|gsha224sum|gsha256sum|gsha384sum|gsha512sum|gshred|gshuf|gsleep|gsort|gsplit|gstat|gstdbuf|gstty|gsum|gsync|gtac|gtail|gtee|gtest|gtimeout|gtouch|gtr|gtrue|gtruncate|gtsort|gtty|guname|gunexpand|guniq|gunlink|guptime|gusers|gvdir|gwc|gwho|gwhoami|gyes)$
    snippet: g$(echo "$LBUFFER" | gsed -r 's/^.*[;|&&|\|\|](\s*)?//g')
    evaluate: true
    if: (( ${+commands$(echo [$(ls $(brew --prefix)/opt/coreutils/bin | grep "^g" | xargs echo | sed -r 's/\s/\]\[/g')])} )) # => (( ${+commands[g[][gb2sum][gbase32][gbase64][gbasename][gbasenc][gcat][gchcon][gchgrp][gchmod][gchown][gchroot][gcksum][gcomm][gcp][gcsplit][gcut][gdate][gdd][gdf][gdir][gdircolors][gdirname][gdu][gecho][genv][gexpand][gexpr][gfactor][gfalse][gfmt][gfold][ggroups][ghead][ghostid][gid][ginstall][gjoin][gkill][glink][gln][glogname][gls][gmd5sum][gmkdir][gmkfifo][gmknod][gmktemp][gmv][gnice][gnl][gnohup][gnproc][gnumfmt][god][gpaste][gpathchk][gpinky][gpr][gprintenv][gprintf][gptx][gpwd][greadlink][grealpath][grm][grmdir][gruncon][gseq][gsha1sum][gsha224sum][gsha256sum][gsha384sum][gsha512sum][gshred][gshuf][gsleep][gsort][gsplit][gstat][gstdbuf][gstty][gsum][gsync][gtac][gtail][gtee][gtest][gtimeout][gtouch][gtr][gtrue][gtruncate][gtsort][gtty][guname][gunexpand][guniq][gunlink][guptime][gusers][gvdir][gwc][gwho][gwhoami][gyes]} ))
```

Is it possible...?

**Comment by Ryooooooga** [comment]
I just added two environment variables: `$current_command` and `$current_buffer` #9.

When `LBUFFER="echo a; git c"`, `current_command="git c"` and `current_abbr="c"` (if `global: false`, always `current_command == current_abbr`).

By using this, it can be written as following:
```yaml
  - abbr-pattern: '' # matches all command
    snippet: g${current_abbr}
    evaluate: true
    if: '[[ -e "$(brew --prefix)/opt/coreutils/bin/g$current_abbr" ]]'
```
